language: node_js
notifications:
  email:
  - yiminghe@gmail.com
node_js:
- 0.11
before_script:
- npm start &
- npm install mocha-phantomjs -g
- phantomjs --version
script:
- npm test
- npm run-script browser-test
- npm run-script browser-test-cover
- npm run saucelabs
env:
  global:
  - secure: WeXiz+R/y4JYq7/Ub2y12R3HtxPKoAWjO4mS4uLvvzkqUmHvmPw5qy6k5ennXDlSa/hq7QXFdgoUoAW/n/GQIF4Zg4Rt91O8uvUs+SJ7amcIY9Ll2AdRg3XqV9LsaUYXT0gTcb1gcpcSTLY5UOhFyXn47A4+mdxrCH8j5DYqEFw=
  - secure: okM6j9WLfOtWctOhm1FqCaePwkoO/PI65dsvXK40XkiymuzcdQiYh/ehlkMgm2kjE8lRCRtzSCdmIEwAUTEBMwUq453Y1dvZxwpoNDodoO8c76BAO9waCURz+3DQKXfRAL9pfDayHx9si/NlLjwhrr9CfyyHt3UYdyqBH5+Zhkw=
